### ISSUE TITLE
Unable to navigate to selected file

### ISSUE THREAD

**Issue by fadeevab** [jaydenlin/ctags-support#6]
VS Code: 1.12.1

Nothing happens when select the item in ctags list. There is an exception:

```
Cannot read property 'filePath' of null: TypeError: Cannot read property 'filePath' of null
    at navigationHistory.map (~/.vscode/extensions/jaydenlin.ctags-support-1.0.17/out/src/extension.js:119:20)
    at Array.map (native)
    at recordHistory (~/.vscode/extensions/jaydenlin.ctags-support-1.0.17/out/src/extension.js:117:27)
    at vscode.window.showQuickPick.then.val (~/.vscode/extensions/jaydenlin.ctags-support-1.0.17/out/src/extension.js:104:13)
    at Object.m [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:62432)
    at Object.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:66006)
    at n.Class.derive._oncancel._run (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:67834)
    at n.Class.derive._oncancel._completed (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:67275)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:73909
    at n.Class.derive._creator.done (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:69135)
```

**Comment by jaydenlin** [comment]
Hi @fadeevab,
Sorry for reply late. Are you try to access the navigation history (cmd+shit+t) and got the error ?
If so, please try to clear the navigation history. Because I change the file format in the new version.

**Clear the navigation history**
Step 1.  press `F1`
Step 2.  Type `clear the navigation history`

http://i.imgur.com/DJA8Myc.png

If you still get problem, please let me know.
Thx!

**Comment by fadeevab** [comment]
It helps! Thank you!

**Comment by tycooon** [comment]
Hi @jaydenlin, for some reason I started to get the same error recently. Clearing history doesn't help for some reason.
